version: "3.7"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Scrappy7737!
      - MYSQL_DATABASE=pageifytest
      - MYSQL_USER=d3vhound
      - MYSQL_PASSWORD=Scrappy7737!
    ports:
      - "3306:3306"
  web:
    image: pageify-test3
    depends_on:
      - db
    ports:
      - "9000:9000"